### PR TITLE
Add more features

### PR DESCRIPTION
**Pull request by agamemnonc**
Just added some more features. Any feedback is most welcome. 

Added features:
- mean value (useful sometimes for signals other than EMG (e.g. accelerometer etc.))
- variance
- wilson amplitude
- skewness
- kurtosis
- auto-regressive coefficients
- sample entropy
- Hjorth parameters 
- Histogram

Important notes
-----------------
### Output shape
Some features (i.e., AR coefficients, Histogram, Hjorth parameters) extract multiple features per channel. Not sure what the best output shape should be in this case. Currently the output array has the same dimensionality as the input when `keepdims=False` or one more axis when `keepdims=True`. 

The shape of the output depends on the input format. For example, for input of `shape = (n_channels, n_samples)`, the output will have `shape = (n_channels, n_features_per_channel)` when `keepdims = False` or `(n_channels, 1, n_features_per_channel)` when `keepdims = True`; for input of `shape = (n_samples, n_channels)` the output will have `shape = (n_features_per_channel, n_channels)` when `keepdims=False` or `(1, n_features_per_channel, n_channels)` when `keepdims=True`. 

An alternative would be to reshape at the end so that the output has `shape = (n_channels*n_features_per_channel)` or `(n_channels*n_features_per_channel, 1)' / `(1, n_channels*n_features_per_channel)' when `keepdims=True`. The downside with this would be that information about which channel is responsible for which feature is lost, which might be useful further down the pipeline, should e.g. the user need to perform channel selection. 

@ixjlyons  what are your thoughts on this?

### Open-source code re-use acknowledgement

The `ar` code makes use of the levinson-durbin algorithm code taken from [here](https://github.com/cokelaer/spectrum/blob/master/src/spectrum/levinson.py);
and `sample_entropy` uses code from [the wikipedia article](https://en.wikipedia.org/wiki/Sample_entropy). 

@ixjlyons Do you have any objections regarding code re-use? If you are happy with that, do you thikn we should acknowledge the original sources somehow?

### CODE REVIEW

**Comment by ixjlyons** [comment]
Really sorry to leave this sitting for so long. Looks great on a first pass. I'll review more thoroughly soon, but one thing I noticed so far: I would probably avoid nested functions, especially for feature functions which may be called repeatedly/rapidly because I believe child function objects are created each time the parent method is called. I would say just push those nested functions out to the module level scope and keep them private.

**Comment by agamemnonc** [comment]
Agreed -- I will change this and push changes through soon.

**Comment by ixjlyons** [comment]
Sorry once again for the long delay and thanks for your patience -- it's really inexcusable to let this sit so long. I'll try to be better about reviewing things quickly if you're still interested in contributing and working on this. Anyway, I'm back to work here and I have a few high-level thoughts about this and some nit-picky things I think we can get to later on.

Probably the most important thing about this is the decision about how many and which features to include in AxoPy. I've always appreciated how scikit-learn follows some guidelines for deciding what to include and not include. As far as I'm concerned, having a collection of very well-established features is reasonable. These seem reasonable to me. I'd appreciate your thoughts about this.

When I originally worked on the features module (pre-dating axopy), I was imagining there being a small handful of submodules like `time.py` and `frequency.py`, maybe `entropy.py` or even `fractal.py`. But then there's a whole other ways to dichotomize features like ones that output a scalar per channel vs. inter-channel correlations and such. I don't really know how much I still care about this organization (obviously I only got as far as `time.py`:)), but I'd be interested in hearing your thoughts on this. In the end, all of the feature functions are available at the `axopy.features` namespace, so it doesn't really matter too much. I just don't really want to have one massive file `.py` file with tons of features.

> Some features (i.e., AR coefficients, Histogram, Hjorth parameters) extract multiple features per channel. Not sure what the best output shape should be in this case. Currently the output array has the same dimensionality as the input when `keepdims=False` or one more axis when `keepdims=True`.
>
> The shape of the output depends on the input format. For example, for input of `shape = (n_channels, n_samples)`, the output will have `shape = (n_channels, n_features_per_channel)` when `keepdims = False` or `(n_channels, 1, n_features_per_channel)` when `keepdims = True`; for input of `shape = (n_samples, n_channels)` the output will have `shape = (n_features_per_channel, n_channels)` when `keepdims=False` or `(1, n_features_per_channel, n_channels)` when `keepdims=True`.
>
> An alternative would be to reshape at the end so that the output has `shape = (n_channels*n_features_per_channel)` or `(n_channels*n_features_per_channel, 1)' / `(1, n_channels*n_features_per_channel)' when `keepdims=True`. The downside with this would be that information about which channel is responsible for which feature is lost, which might be useful further down the pipeline, should e.g. the user need to perform channel selection.

My plan was, had I gotten to adding AR coefficients or similar features with multiple values per channel, to flatten the output so that, for inputs with shape `(n_channels, n_samples)`, you'd output an array with shape `(n_channels*n_samples,)` (unless `keepdims=True`). So that leaves a decision on the ordering. I'd say it makes some sense to do:

```
F1/Ch1  F1/Ch2  F1/Ch3  ...  F1/ChC  F2/Ch1  F2/Ch2  ...
```

It does seem somewhat arbitrary though. My primary reasoning for flattening would be that this output can directly be concatenated together with a windower and then fed to scikit-learn estimators and transformers and such. The ability to inspect data as it goes through various pieces of AxoPy is certainly lacking. I actually recently discovered [this](https://github.com/pyqtgraph/pyqtgraph/tree/develop/pyqtgraph/metaarray), which seems like it could be useful. If you have thoughts or ideas, feel free to email me or open an issue.


> The `ar` code makes use of the levinson-durbin algorithm code taken from [here](https://github.com/cokelaer/spectrum/blob/master/src/spectrum/levinson.py);
and `sample_entropy` uses code from [the wikipedia article](https://en.wikipedia.org/wiki/Sample_entropy).
>
> @ixjlyons Do you have any objections regarding code re-use? If you are happy with that, do you thikn we should acknowledge the original sources somehow?

I'm fine with code re-use. You raise a good point I hadn't really thought much about though. I think we should either localize the credit to the functions being re-used or put the functions in their own hidden submodule and write a docstring that gives credit for the whole file. In any case, I think it's useful to make the line between original and re-used code as clean as possible. Let's do a separate module for any code source for now and see how that goes.

A few years ago I worked on implementing a few different entropy features: https://github.com/ixjlyons/entro-py. If I remember correctly, I had a bit of trouble re-producing a plot in a paper on cross fuzzy entropy. Anyway, check that out if you're interested, I think I ended up with a reasonably efficient and general way to compute those features. I always thought about implementing with plain loops using Cython and seeing how that performs compared to a semi-vectorized version.


On the `normalize_axis_index` thing: I haven't taken a close look at what it's used for here, but is there a reasonable alternative? NumPy 1.13 is a couple years old, but I'd prefer not to have such a recent minimum version if possible. It's also a rather hidden as it looks like it's mostly for internal use.


Like I mentioned earlier, I will finish reviewing the code more thoroughly. Sorry again for letting this go. Smaller PRs are probably preferable mostly because it'd help me review them more efficiently. Me taking this long isn't your fault though, I've been putting it off.

**Comment by agamemnonc** [comment]
Hi, thanks for getting back on this.

> Probably the most important thing about this is the decision about how many and which features to include in AxoPy. I've always appreciated how scikit-learn follows some guidelines for deciding what to include and not include. 

Agreed! 

> When I originally worked on the features module (pre-dating axopy), I was imagining there being a small handful of submodules like `time.py` and `frequency.py`, maybe `entropy.py` or even `fractal.py`. But then there's a whole other ways to dichotomize features like ones that output a scalar per channel vs. inter-channel correlations and such. I don't really know how much I still care about this organization (obviously I only got as far as `time.py`:)), but I'd be interested in hearing your thoughts on this. In the end, all of the feature functions are available at the `axopy.features` namespace, so it doesn't really matter too much. I just don't really want to have one massive file `.py` file with tons of features.

This approach sounds good to me, however it might be a bit difficult to categorise some of the features. For example, AR coefficients are extracted in the time domain (there is no FFT or anything like that) but they really contain frequency information, so I am not really sure where they would go. Same holds for histogram features I would say. But we could decide that whatever is extracted in the time domain goes into `time.py`, anything that uses spectrograms etc goes into `frequency.py` and so on. But then again, we might as well end up with a long `time.py` file :)

> My plan was, had I gotten to adding AR coefficients or similar features with multiple values per channel, to flatten the output so that, for inputs with shape `(n_channels, n_samples)`, you'd output an array with shape `(n_channels*n_samples,)` (unless `keepdims=True`).... My primary reasoning for flattening would be that this output can directly be concatenated together with a windower and then fed to scikit-learn estimators and transformers and such. 

I think I now agree with you on this.

> So that leaves a decision on the ordering. I'd say it makes some sense to do:
> 
> ```
> F1/Ch1  F1/Ch2  F1/Ch3  ...  F1/ChC  F2/Ch1  F2/Ch2  ...
> ```
> It does seem somewhat arbitrary though.

This ordering makes more sense to me too, the reason being that if multiple features are combined further down through concatenation (say e.g MAV with AR order 3) this: 
```
MAV/Ch1 MAV/Ch2.. MAV/ChC, AR1/Ch1 AR1/Ch2 ... AR1/ChC AR2/Ch1 AR2/Ch2 ... AR2/ChC AR3/Ch1 AR3/Ch2...AR3/ChC 
```
would probably make more sense than this: 
```
MAV/Ch1 MAV/Ch2.. MAV/ChC, AR1/Ch1 AR2/Ch1 AR3/Ch1 AR1/Ch2 AR2/Ch2 AR3/Ch2... AR1/ChC AR2/ChC AR3/ChC
```

> The ability to inspect data as it goes through various pieces of AxoPy is certainly lacking. I actually recently discovered [this](https://github.com/pyqtgraph/pyqtgraph/tree/develop/pyqtgraph/metaarray), which seems like it could be useful. If you have thoughts or ideas, feel free to email me or open an issue.

That's actually a potentially very good idea. 
Do you think something like this would work? If so, would it be possible you think to refactor the feature extraction code without breaking everything? 

```python
import numpy as np

class FeatureArray(np.ndarray):
    """"A numpy array with additional information. 
    
    Parameters
    ----------
    
    data : array, shape = (n_features,)
        The extracted feature data.
    
    channels : list
        A list of length n_features where each element indicates the channel
        that the feature originates from.
    
     **kwargs : key, value mappings
         Keyword arguments that are passed through to the creation of the
         array.
    """
    
    def __new__(cls, data, channels=None, **kwargs):
        obj = np.asarray(data, **kwargs).view(cls)
        obj.channels = channels
        return obj

    def __array_finalize__(self, obj):
        if obj is None: return
        self.channel = getattr(obj, 'channel', None)
```
```python
# Example   
np.random.seed(10)

ar_order = 4
n_channels = 5

farr = FeatureArray(data=np.random.randn(n_channels,),
                    channels=np.tile(range(n_channels), ar_order),
                    dtype=np.float32)

print(farr)
print(farr.channels)
```
Output
```
[ 1.3315865   0.715279   -1.5454003  -0.00838385  0.621336  ]
[0 1 2 3 4 0 1 2 3 4 0 1 2 3 4 0 1 2 3 4]
```

> I'm fine with code re-use. You raise a good point I hadn't really thought much about though. I think we should either localize the credit to the functions being re-used or put the functions in their own hidden submodule and write a docstring that gives credit for the whole file. In any case, I think it's useful to make the line between original and re-used code as clean as possible. Let's do a separate module for any code source for now and see how that goes.

Sure.

> 
> A few years ago I worked on implementing a few different entropy features: https://github.com/ixjlyons/entro-py. If I remember correctly, I had a bit of trouble re-producing a plot in a paper on cross fuzzy entropy. Anyway, check that out if you're interested, I think I ended up with a reasonably efficient and general way to compute those features. I always thought about implementing with plain loops using Cython and seeing how that performs compared to a semi-vectorized version.

Ah thanks for this. Sure, we could use your implentation. Would you prefer adding a dependency, or perhaps adding an `externals` submodule to include this and any other dependencies? 

> On the `normalize_axis_index` thing: I haven't taken a close look at what it's used for here, but is there a reasonable alternative? NumPy 1.13 is a couple years old, but I'd prefer not to have such a recent minimum version if possible. It's also a rather hidden as it looks like it's mostly for internal use.

Let's forget about why I used this before. If we agree to flatten the output of features that extract multiple values per channel, we need to differentiate between the cases where the data are stored as `(n_channels, n_samples)` or `(n_samples, n_channels)`. For the first case, the `order` parameter of `flatten()` should be `"f"` (as feature matrix has shape `(n_channels, n_features_per_channel)`) and in the second case it should be `"c"` (feature matrix has shape `(n_features_per_channel, n_channels)`). 

Now the only reason to use `normalize_axis_index` would be to avoid using an `if` statement and also be able support both `axis=1` and `axis=-1` when the data have shape `(n_channels, n_samples)`, as in both cases `normalize_axis_index` will return `1`. 

Alternatively, we can just use an `if` statement (we are restricting ourselves to 2D data only anyway, so this should be OK):
```python
if axis == -1 or axis == 1:
    order = 'f'
elif axis == 0:
   order = 'c'
```

**Comment by ixjlyons** [comment]
> This approach sounds good to me, however it might be a bit difficult to categorise some of the features. For example, AR coefficients are extracted in the time domain (there is no FFT or anything like that) but they really contain frequency information, so I am not really sure where they would go. Same holds for histogram features I would say. But we could decide that whatever is extracted in the time domain goes into time.py, anything that uses spectrograms etc goes into frequency.py and so on. But then again, we might as well end up with a long time.py file :)

Yeah all good points. I'm ok with punting on this decision and leaving everything in a single module right now. Again, since it's exposed via `axopy.features`, I'd expect that to be the most used. Perhaps it's worth opening an issue to form a list of good candidates for features to add and maybe ways they could be categorized (or not).

> That's actually a potentially very good idea.
> Do you think something like this would work? If so, would it be possible you think to refactor the feature extraction code without breaking everything?

That looks pretty cool. Let's discuss more in a separate issue. I don't think there's a whole lot to break. The feature extraction functions are purposefully plain functions that you can wrap to put in a `Pipeline`. There's [`FeatureExtractor`](https://axopy.readthedocs.io/en/latest/api/pipeline.html#axopy.pipeline.FeatureExtractor) but it's not all that useful so I'd be happy to replace it with something nicer.

> Ah thanks for this. Sure, we could use your implentation. Would you prefer adding a dependency, or perhaps adding an externals submodule to include this and any other dependencies?

I was more just pointing it out if you're interested. Like I mentioned, I remember not quite being sure about the implementation being correct, so a little tinkering is probably needed before adding it.

> Let's forget about why I used this before. If we agree to flatten the output of features that extract multiple values per channel, we need to differentiate between the cases where the data are stored as (n_channels, n_samples) or (n_samples, n_channels). For the first case, the order parameter of flatten() should be "f" (as feature matrix has shape (n_channels, n_features_per_channel)) and in the second case it should be "c" (feature matrix has shape (n_features_per_channel, n_channels)).

Got it, that makes sense.

> Now the only reason to use normalize_axis_index would be to avoid using an if statement and also be able support both axis=1 and axis=-1 when the data have shape (n_channels, n_samples), as in both cases normalize_axis_index will return 1.
> 
> Alternatively, we can just use an if statement (we are restricting ourselves to 2D data only anyway, so this should be OK):
> ```
> if axis == -1 or axis == 1:
>     order = 'f'
> elif axis == 0:
>    order = 'c'
> ```
> Another option would be to have an axis checker function like the following one that is called from every feature extraction function:
> ```
> def check_axis(axis):
>     """TODO: docstring.
>     """
> 
>     if axis not in [-1, 0, 1]:
>         raise ValueError("Invalid axis.")
>         
>     return np.abs(axis)
> ```
> The obvious drawback with both approaches is that this function would be repetitively called every time feature extraction takes place which is unnecessary.

Yeah, I sort of avoided putting in lots of array checking type stuff for this reason, assuming "I know what I'm doing" -- i.e. I know the shapes of arrays I'm passing in and such. It turns out to be a bit of a headache to verify transformations through pipelines with many steps, so better checking (and error/warning messages) would be great. It's also possible to add a `skipchecks` keyword argument for cases where you're running low on idle time between updates.

Another point worth mentioning is I originally had the feature functions in a separate repository, and before that, it was part of the predecessor to AxoPy. So, I've flipped back and forth on the decision on whether or not to include features in AxoPy itself. I ended up bringing it back in with the idea that I could keep them relatively de-coupled from the rest of AxoPy. This would allow you to use them for post-processing or whatever, and you also have the flexibility of deciding what shape you prefer for your data (i.e. `(n_samples, n_channels)` vs `(n_channels, n_samples)`). If there's consistent pain and overhead in dealing with input data that could be in arbitrary shape and processing along any given axis, it might make sense to be more strict about the expected shape of data. The current data acquisition devices I've written output ndarrays `(n_channels, n_samples)`, so that's sort of the default I chose. Perhaps it's time to roll our own time series array implementation, or use [Nitime](http://nipy.org/nitime/index.html) or something.

**Comment by agamemnonc** [comment]
I implemented the topics we have discussed (sorry it took sooo long!)

Please let me know if something doesn't look good.

Some notes:
* I had to increase the number of data points `n=100` in tests, because `sample_entropy` wouldn't work with few  data points. This has resulted in an increase in the time required for the tests (currently 3.5 s). Please let me know if this is too long and you'd rather find a way of reducing it (e.g. perform tests for all functions but `sample_entropy` with `n=10` and then have a separate test for this function with more data points).

* Functions that extract multiple features per channel (e.g. AR) currently support only 1-d or 2-d input data (whereas other functions can in principle handle higher-dimensional data too). This is due to the choice of flattening the output (for higher than 2-d, output flattening would be ambiguous)  

* I have included a function `ensure_1d()` similar to `ensure_2d()` cos I thought it would be useful at some point but it turned out not to be. I can remove it if you think is redundant. 

* On a similar note, I have noticed that `ensure_2d()` is not really used so removed the import from `time.py`. Could put it back if you think there is a reason it should be there.

* I included all re-used code in a module called `external` with one file per source and copied the license and source at the docstring. Please let me know if you are not happy with this format.

* I decided to discard the idea we discussed about `FeatureArray` as I realised that feature/channel selection would probably be possible using the `FeatureExtraction` class. I will open a different issue about this and we shall discuss there.

* Tests are failing with message: 
"The command "pytest --cov" exited with 134."
Not really sure the cause of this.

**Comment by ixjlyons** [comment]
I'm away for the weekend but I will get to this early next week. I'm inclined to just go ahead and merge and address a couple of your points above later, but I'll take a closer look since there are still a few pieces I haven't really reviewed at all.

**Comment by agamemnonc** [comment]
Great, thanks!

No rush at all -- I suggest we take our time with this since it will require some API-related decision making :)

**Comment by agamemnonc** [comment]
Closing this due to inactivity.

**Pull request closed without merging**
